module.exports = [
  {
    id: "1",
    productName: 'Stretch Washed Chinos',
    productCategory: 'bottoms',
    productPrice: 2500,
  },
  {
    id: "2",
    productName: 'Tech Chinos',
    productCategory: 'bottoms',
    productPrice: 2000,
  },
  {
    id: "3",
    productName: 'Weekday Warriors',
    productCategory: 'bottoms',
    productPrice: 1500,
  },
  {
    id: "4",
    productName: 'Stretch Denim',
    productCategory: 'bottoms',
    productPrice: 1000,
  },
  {
    id: "5",
    productName: 'Fleece Joggers',
    productCategory: 'bottoms',
    productPrice: 500,
  },
  {
    id: "6",
    productName: 'Banzai Shorts',
    productCategory: 'bottoms',
    productPrice: 500,
  },
  {
    id: "7",
    productName: 'Riviera Short Sleeve',
    productCategory: 'tops',
    productPrice: 2000,
  },
  {
    id: "8",
    productName: 'Stretch Oxford',
    productCategory: 'tops',
    productPrice: 1500,
  },
  {
    id: "9",
    productName: 'Tech Button-Down',
    productCategory: 'tops',
    productPrice: 1500,
  },
  {
    id: "10",
    productName: 'Chore Jacket',
    productCategory: 'outerwear',
    productPrice: 1000,
  },
  {
    id: "11",
    productName: 'Military jacket',
    productCategory: 'outerwear',
    productPrice: 1000,
  },
  {
    id: "12",
    productName: 'Topcoat',
    productCategory: 'outerwear',
    productPrice: 500,
  },
  {
    id: "13",
    productName: 'Jetsetter Stretch Wool',
    productCategory: 'suits',
    productPrice: 1000,
  },
  {
    id: "14",
    productName: 'Jetsetter Stretch Italian Wool',
    productCategory: 'suits',
    productPrice: 500,
  },
  {
    id: "15",
    productName: 'Italian Performance',
    productCategory: 'suits',
    productPrice: 1000,
  },
  {
    id: "16",
    productName: 'Silk Tie',
    productCategory: 'accessories',
    productPrice: 500,
  },
  {
    id: "17",
    productName: 'Linen Pocket Square',
    productCategory: 'accessories',
    productPrice: 500,
  },
  {
    id: "18",
    productName: 'Jeans Belt',
    productCategory: 'accessories',
    productPrice: 500,
  },
]
